####################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
####################################################################################################

application:
  enable-perf-measurement: 1
  perf-measurement-interval-sec: 5
  ##gie-kitti-output-dir=streamscl

tiled-display:
  enable: 1
  rows: 2
  columns: 2
  width: 1920
  height: 1080
  gpu-id: 0
  #(0): nvbuf-mem-default - Default memory allocated, specific to particular platform
  #(1): nvbuf-mem-cuda-pinned - Allocate Pinned/Host cuda memory, applicable for Tesla
  #(2): nvbuf-mem-cuda-device - Allocate Device cuda memory, applicable for Tesla
  #(3): nvbuf-mem-cuda-unified - Allocate Unified cuda memory, applicable for Tesla
  #(4): nvbuf-mem-surface-array - Allocate Surface Array memory, applicable for Jetson
  nvbuf-memory-type: 0

source:
  csv-file-path: sources_egg.csv

sink0:
  enable: 1
  #Type - 1=FakeSink 2=EglSink/nv3dsink (Jetson only) 3=File
  type: 2
  sync: 0
  source-id: 0
  gpu-id: 0
  nvbuf-memory-type: 0
  link-to-demux: 0

sink1:
  enable: 0
  type: 3
  #1=mp4 2=mkv
  container: 1
  #1=h264 2=h265
  codec: 1
  #encoder type 0=Hardware 1=Software
  enc-type: 0
  sync: 0
  #iframeinterval=10
  bitrate: 2000000
  #H264 Profile - 0=Baseline 2=Main 4=High
  #H265 Profile - 0=Main 1=Main10
  # set profile only for hw encoder, sw encoder selects profile based on sw-preset
  profile: 0
  output-file: out.mp4
  source-id: 0


sink2:
  enable: 0
  #Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming
  type: 4
  #1=h264 2=h265
  codec: 1
  #encoder type 0=Hardware 1=Software
  enc-type: 0
  sync: 1
  bitrate: 4000000
  #H264 Profile - 0=Baseline 2=Main 4=High
  #H265 Profile - 0=Main 1=Main10
  # set profile only for hw encoder, sw encoder selects profile based on sw-preset
  profile: 2
  # set below properties in case of RTSPStreaming
  rtsp-port: 8554
  udp-port: 5400
  link-to-demux: 1
  source-id: 0
  
sink3:
  enable: 1
  #Type - 1=FakeSink 2=EglSink 3=File 4=RTSPStreaming
  type: 6
  sync: 1
  link-to-demux: 0
  source-id: 0
  msg-conv-config: msgconv_config.txt
  #(0): PAYLOAD_DEEPSTREAM - Deepstream schema payload
  #(1): PAYLOAD_DEEPSTREAM_MINIMAL - Deepstream schema payload minimal
  #(256): PAYLOAD_RESERVED - Reserved type
  #(257): PAYLOAD_CUSTOM   - Custom schema payload
  msg-conv-payload-type: 1
  msg-conv-msg2p-lib: ../../nvmsgconv/libnvds_msgconv_custom.so
  msg-broker-proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_mqtt_proto.so
  #Provide your msg-broker-conn-str here
  msg-broker-conn-str: localhost;1883;
  msg-conv-frame-interval: 100
  topic: egg_count
  #Optional:
  #msg-broker-config=../../deepstream-test4/cfg_kafka.txt
  new-api: 1
  msg-conv-msg2p-new-api: 1

osd:
  enable: 1
  gpu-id: 0
  border-width: 1
  text-size: 15
  #value changed
  text-color: 1;1;1;1
  text-bg-color: 0.3;0.3;0.3;1
  font: Serif
  show-clock: 0
  clock-x-offset: 800
  clock-y-offset: 820
  clock-text-size: 12
  clock-color: 1;0;0;0
  nvbuf-memory-type: 0

streammux:
  gpu-id: 0
  ##Boolean property to inform muxer that sources are live
  live-source: 0
  buffer-pool-size: 8
  batch-size: 8
  ##time out in usec, to wait after the first buffer is available
  ##to push the batch even if the complete batch is not formed
  batched-push-timeout: 40000
  ## Set muxer output width and height
  width: 1920
  height: 1080
  ##Enable to maintain aspect ratio wrt source, and allow black borders, works
  ##along with width, height properties
  enable-padding: 0
  nvbuf-memory-type: 0

primary-gie:
  enable: 1
  gpu-id: 0
  gie-unique-id: 1
  #Required by the app for OSD, not a plugin property
  bbox-border-color0: 1;0;0;1
  bbox-border-color1: 0;1;1;1
  bbox-border-color2: 0;0;1;1
  bbox-border-color3: 0;1;0;1
  nvbuf-memory-type: 0
  config-file: config_pgie.txt

tracker:
  enable: 1
  # For NvDCF and NvDeepSORT tracker, tracker-width and tracker-height must be a multiple of 32, respectively
  tracker-width: 640
  tracker-height: 384
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
  # ll-config-file required to set different tracker types
  # ll-config-file: config_tracker_IOU.yml
  # ll-config-file: config_tracker_NvSORT.yml
  ll-config-file: config_tracker_NvSORT.yml
  # ll-config-file: config_tracker_NvDCF_accuracy.yml
  # ll-config-file: config_tracker_NvDeepSORT.yml
  gpu-id: 0
  display-tracking-id: 0

nvds-analytics:
  enable: 1
  config-file: config_nvdsanalytics.txt

tests:
  file-loop: 0
